# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  # desc "Submit a new Beta Build to Crashlytics Beta"
  # lane :beta do
    # gradle(task: "clean assembleRelease")
    # crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  # end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Deploy a beta version to Mobile Center"
  lane :beta do
      gradle(
        task: "assemble",
        build_type: "debug"
      )
      changelog = changelog_from_git_commits(commits_count: 1)

      android_set_version_code

      mobile_center_upload(
        api_token: "3167558d823d76048952dd3484138c87e5e543da",
        owner_name: "james.hughes-magentys.io",
        app_name: "ButtonClickApp",
        apk: "app/build/outputs/apk/debug/app-debug.apk",
        release_notes: changelog
      )
  end

end
